services:
  # 1. The Redis service (unchanged)
  redis:
    image: redis:7.2-bookworm
    container_name: nb-monitor-redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nb-monitor-network

  # 2. The NEW API Server Service
  api-server:
    build: .
    container_name: nb-monitor-api
    restart: always
    command: node api-server.js # <-- Overrides the Dockerfile's default CMD
    ports:
      - "5003:3000" # <-- This is your PUBLIC endpoint for the frontend
    env_file:
      - ../../.env.local
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - nb-monitor-network

  # 3. The Worker Service (updated)
  worker:
    build: . # It can use the same image as the API server
    container_name: nb-monitor-worker
    restart: always
    command: node sql-worker.js # <-- Explicitly tells it to run the worker script
    env_file:
      - ../../.env.local
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - nb-monitor-network

# The private network (unchanged)
networks:
  nb-monitor-network:
    name: nb-monitor-network